# Generated by Django 5.1.6 on 2025-02-12 01:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 12, 1, 25, 4, 202990, tzinfo=datetime.timezone.utc), verbose_name='作成日時'),
        ),
    ]
