# Generated by Django 5.1.6 on 2025-03-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_tag_diary_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='tags',
            field=models.ManyToManyField(blank=True, to='diary.tag', verbose_name='タグ'),
        ),
    ]
